=== woonyzzang/j-portfolio/public/dev/listmap/dtd/listmap.dtd
<!ELEMENT items (tit,project,workers,lst*)>
<!ELEMENT workers (worker)>
<!ELEMENT lst (area,prenum,section,item,planningID,markupURL,worker,progress,complete,planningValid,designValid,ex)>
<!ELEMENT tit (#PCDATA)>
<!ELEMENT area (#PCDATA)>
<!ELEMENT prenum (#PCDATA)>
<!ELEMENT section (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT planningID (#PCDATA)>
<!ELEMENT markupURL (#PCDATA)>
<!ELEMENT worker (#PCDATA)>
<!ELEMENT progress (#PCDATA)>
<!ELEMENT complete (#PCDATA)>
<!ELEMENT planningValid (#PCDATA)>
<!ELEMENT designValid (#PCDATA)>
<!ELEMENT ex (#PCDATA)>
<!ATTLIST items title CDATA #IMPLIED>
<!ATTLIST project year CDATA #REQUIRED>
<!ATTLIST worker color CDATA #REQUIRED>
<!ATTLIST markupURL link CDATA #REQUIRED type CDATA #REQUIRED>

=== woonyzzang/j-portfolio/public/dev/listmap/listmap.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="xsl/listmap.xsl"?>
<!DOCTYPE items SYSTEM "dtd/listmap.dtd">

<!-- ## List Map[ver 1.0] ##
 * #Date		: 2013.01.19
 * #Developer	: Joe Seung Woon
 *
 * @items[title] : 문서 타이틀
 * @items>tit : 회사명
 * @items>project : 프로젝트명 타이틀
 * @items>project[year] : 작업연도
 *
 * @workers>worker[id] : 작업자 이니셜
 * @workers>worker[bgcolor] : 작업자 배경 컬러
 * @workers>worker[fcolor] : 작업자 폰트 컬러
 *
 * @items>lst[worker] : 작업자이름
 * @items>lst[nickname] : 작업자 이니셜(@workers>worker[id]값과 일치해야함)
 * @items>lst>area : 구분
 * @items>lst>prenum : 우선순위
 * @items>lst>section : 섹션
 * @items>lst>item : 항목
 * @items>lst>planningID : 기획서ID
 * @items>lst>doc>link : HTML 마크업 파일
 * @items>lst>doc>link[url] : 링크 주소
 * @items>lst>doc>link[progress] : 진핸현황
 * @items>lst>doc>link[doctype] : 문서타입(확장자)
 * @items>lst>complete : 완료일
 * @items>lst>complete[date] : 완료 상세 날짜
 * @items>lst>planningValid : 기획검수 완료(true)/미완료(false)
 * @items>lst>designValid : 디자인검수 완료(true)/미완료(false)
 * @items>lst>ex : 비고
 * @items>lst>ex[tag] : 배포태그 생성(show)/제거(hide)
-->

<items title="List Map : BlueWaves">
	<tit>BlueWaves</tit>
	<project year="2013">프로젝트 명</project>

	<workers>
		<worker id="worker1" bgcolor="#f63" fcolor="#f63" >작업자1</worker>
		<worker id="worker2" bgcolor="#4b2" fcolor="#4b2">작업자2</worker>
		<worker id="worker3" bgcolor="#59d" fcolor="#59d">작업자3</worker>
	</workers>

	<lst worker="작업자1" nickname="worker1">
		<area>ex)메인</area>
		<prenum>1</prenum>
		<section>메인</section>
		<item>홈</item>
		<planningID>file.pop.01</planningID>
		<doc>
			<link url="#" progress="80" doctype="html">index</link>
		</doc>
		<complete date="2013-01-13">02.13</complete>
		<planningValid>true</planningValid>
		<designValid>false</designValid>
		<ex tag="show">1차 배포 02.03</ex>
	</lst>
	<lst worker="작업자2" nickname="worker2">
		<area>ex)가이드</area>
		<prenum>2</prenum>
		<section>팝업</section>
		<item>레이어</item>
		<planningID>file.pop.07</planningID>
		<doc>
			<link url="#" progress="100" doctype="php">pop</link>
			<link url="#" progress="60" doctype="php">pop2</link>
			<link url="#" progress="20" doctype="php">pop3</link>
		</doc>
		<complete date="2013-02-13">02.13</complete>
		<planningValid>true</planningValid>
		<designValid>true</designValid>
		<ex tag="hide"></ex>
	</lst>
	<lst worker="작업자3" nickname="worker3">
		<area>ex)서브</area>
		<prenum>1</prenum>
		<section>사이드</section>
		<item>푸터</item>
		<planningID>file.pop.07</planningID>
		<doc>
			<link url="#" progress="100" doctype="php">sub</link>
		</doc>
		<complete date="2013-02-13">02.13</complete>
		<planningValid>false</planningValid>
		<designValid>true</designValid>
		<ex tag="show">2차 배포 03.14</ex>
	</lst>
</items>
